# Generated by Django 3.2.6 on 2021-08-29 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='users_who_liked',
            field=models.ManyToManyField(blank=True, related_name='users_who_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
