# Generated by Django 3.2.6 on 2021-09-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='artists', to='music.Artist'),
        ),
    ]
